# Generated by Django 4.2.9 on 2024-02-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_categories_options_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
